# This workflow will deploy an unmanaged Kubernetes k3s cluster running on an Azure Virtual Machine

name: Deploy Cluster

# Triggered manually
on:
  workflow_dispatch:
    inputs:
      credentials:
        required: true
        default: "AZURE_CREDENTIALS"
        description: The name of the GitHub Secret to use for deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Azure Login
        uses: Azure/login@v1
        with:
          # See: https://github.com/jasoncabot-ms/arc-for-kubernetes/blob/main/CREATE_CLUSTERS.md
          creds: ${{ secrets[github.event.inputs.credentials] }}

      - name: Deploy a VM running k3s
        run: |
          # Per-repository secrets
          APP_ID=$(echo '${{ secrets[github.event.inputs.credentials] }}' | jq -r '.clientId')
          echo "::add-mask::$APP_ID"
          PASSWORD=$(echo '${{ secrets[github.event.inputs.credentials] }}' | jq -r '.clientSecret')
          echo "::add-mask::$PASSWORD"
          TENANT_ID=$(echo '${{ secrets[github.event.inputs.credentials] }}' | jq -r '.tenantId')
          echo "::add-mask::$TENANT_ID"

          RG=$(az group list -o tsv --query '[0].name')
          echo "::add-mask::$RG"
          SUBSCRIPTION_ID=$(az account show --query 'id' -o tsv)
          echo "::add-mask::$SUBSCRIPTION_ID"

          az deployment group create -g "$RG" -n "${{ github.event_name }}" --template-file "00-setup/azuredeploy.json" --parameters appId="$APP_ID" password="$PASSWORD" tenantId="$TENANT_ID" subscriptionId="$SUBSCRIPTION_ID"
